from config import (
    OPENAI_API_KEY,
    OPENAI_EMBEDDING_DIMENSIONS,
    OPENAI_EMBEDDING_LIMIT,
    OPENAI_EMBEDDING_MODEL,
)

__all__ = [
    "OPENAI_API_KEY",
    "OPENAI_EMBEDDING_DIMENSIONS",
    "OPENAI_EMBEDDING_LIMIT",
    "OPENAI_EMBEDDING_MODEL",
]